In [1]:
from google.colab import drive
drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).


In [2]:
import numpy as np
import torch
import torch.nn as nn
import torch.optim as optim

# Load data
iris = np.genfromtxt('/content/drive/Othercomputers/My Laptop/Advanced/D-Learning/231011/code/iris_1D_2c.csv', dtype=None, delimiter=',', skip_header=1)
X = torch.tensor(iris[:, 0:1], dtype=torch.float32)
y = torch.tensor(iris[:, 1], dtype=torch.int64)

# Define the model
class SoftmaxRegression(nn.Module):
    def __init__(self, input_dim, output_dim):
        super(SoftmaxRegression, self).__init__()
        self.linear = nn.Linear(input_dim, output_dim)

        # set value (for illustration)
        self.linear.weight.data = torch.Tensor([[0.2], [-0.1]])
        self.linear.bias.data = torch.Tensor([0.1, 0.05])

    def forward(self, x):
        return self.linear(x)

input_dim = X.shape[1]
output_dim = len(torch.unique(y))
model = SoftmaxRegression(input_dim, output_dim)

# Loss and optimizer
criterion = nn.CrossEntropyLoss()
optimizer = optim.SGD(model.parameters(), lr=0.1)

# Training loop
max_epoch = 1
for epoch in range(max_epoch):
    for i in range(X.shape[0]):
        xi = X[i].unsqueeze(0)
        yi = y[i].unsqueeze(0)

        print(f'xi: {xi}')
        print(f'yi: {yi}')

        # Zero the gradients
        optimizer.zero_grad()

        # Forward pass
        outputs = model(xi)
        print(f'outputs: {outputs.data}')

        loss = criterion(outputs, yi)
        print(f'loss: {loss}')

        # Backward pass and optimization
        loss.backward()
        optimizer.step()
        break

print(model.linear.weight)
print(model.linear.bias)

xi: tensor([[1.4000]])
yi: tensor([0])
outputs: tensor([[ 0.3800, -0.0900]])
loss: 0.4855092167854309
Parameter containing:
tensor([[ 0.2538],
        [-0.1538]], requires_grad=True)
Parameter containing:
tensor([0.1385, 0.0115], requires_grad=True)


## N Samples

In [3]:
import numpy as np
import torch
import torch.nn as nn
import torch.optim as optim

# Load data
iris = np.genfromtxt('/content/drive/Othercomputers/My Laptop/Advanced/D-Learning/231011/code/iris_1D_2c.csv', dtype=None, delimiter=',', skip_header=1)
X = torch.tensor(iris[:, 0:1], dtype=torch.float32)
y = torch.tensor(iris[:, 1], dtype=torch.int64)

# Define the model
class SoftmaxRegression(nn.Module):
    def __init__(self, input_dim, output_dim):
        super(SoftmaxRegression, self).__init__()
        self.linear = nn.Linear(input_dim, output_dim)

        # set value (for illustration)
        self.linear.weight.data = torch.Tensor([[0.2], [-0.1]])
        self.linear.bias.data = torch.Tensor([0.1, 0.05])

    def forward(self, x):
        return self.linear(x)

input_dim = X.shape[1]
output_dim = len(torch.unique(y))
model = SoftmaxRegression(input_dim, output_dim)

# Loss and optimizer
criterion = nn.CrossEntropyLoss()
optimizer = optim.SGD(model.parameters(), lr=0.1)

# Training loop
max_epoch = 1
for epoch in range(max_epoch):
    # Zero the gradients
    optimizer.zero_grad()

    # Forward pass
    outputs = model(X)
    print(f'outputs: {outputs.data}')

    loss = criterion(outputs, y)
    print(f'loss: {loss}')

    # Backward pass and optimization
    loss.backward()
    optimizer.step()

print(model.linear.weight)
print(model.linear.bias)

outputs: tensor([[ 0.3800, -0.0900],
        [ 0.3600, -0.0800],
        [ 0.4000, -0.1000],
        [ 1.0000, -0.4000],
        [ 0.9200, -0.3600],
        [ 1.0200, -0.4100]])
loss: 1.0411728620529175
Parameter containing:
tensor([[0.0514],
        [0.0486]], requires_grad=True)
Parameter containing:
tensor([0.0794, 0.0706], requires_grad=True)
