#AI VIET NAM
#CNN Basic
**Nguyen Quoc Thai**

In [1]:
import torch
import torch.nn as nn

torch.manual_seed(42)

##**1. Convolutional Layer**

###**1.1. Convolutional Operation**

**Example 1**

In [2]:
input = torch.randint(5, (1, 6, 6), dtype=torch.float32)
input

tensor([[[2., 2., 1., 4., 1., 0.],
         [0., 4., 0., 3., 3., 4.],
         [0., 4., 1., 2., 0., 0.],
         [2., 1., 4., 1., 3., 1.],
         [4., 3., 1., 4., 2., 4.],
         [2., 0., 0., 4., 3., 4.]]])

In [3]:
# define convolutional layer
conv_layer = nn.Conv2d(
    in_channels=1,
    out_channels=1,
    kernel_size=3, # create a kernel: 3 x 3
    bias=False
)

In [4]:
conv_layer.weight

Parameter containing:
tensor([[[[ 0.0520,  0.2693,  0.0364],
          [-0.1051,  0.0896, -0.0904],
          [ 0.1403,  0.2976,  0.1927]]]], requires_grad=True)

In [5]:
init_kernel_weight = torch.randint(
    high=2,
    size=(conv_layer.weight.data.shape),
    dtype=torch.float32
)
init_kernel_weight

tensor([[[[1., 1., 0.],
          [1., 1., 0.],
          [1., 0., 1.]]]])

In [6]:
# init weight
conv_layer.weight.data = init_kernel_weight
conv_layer.weight

Parameter containing:
tensor([[[[1., 1., 0.],
          [1., 1., 0.],
          [1., 0., 1.]]]], requires_grad=True)

In [7]:
output = conv_layer(input)
output

tensor([[[ 9., 13.,  9., 13.],
         [14., 11., 13., 10.],
         [12., 17., 11., 14.],
         [12., 13., 13., 18.]]], grad_fn=<SqueezeBackward1>)

**Example 2**

In [8]:
input

tensor([[[2., 2., 1., 4., 1., 0.],
         [0., 4., 0., 3., 3., 4.],
         [0., 4., 1., 2., 0., 0.],
         [2., 1., 4., 1., 3., 1.],
         [4., 3., 1., 4., 2., 4.],
         [2., 0., 0., 4., 3., 4.]]])

In [9]:
# define convolutional layer
conv_layer = nn.Conv2d(
    in_channels=1,
    out_channels=1,
    kernel_size=3, # create a kernel: 3 x 3
)

In [10]:
init_kernel_weight

tensor([[[[1., 1., 0.],
          [1., 1., 0.],
          [1., 0., 1.]]]])

In [11]:
# init weight
conv_layer.weight.data = init_kernel_weight
conv_layer.weight

Parameter containing:
tensor([[[[1., 1., 0.],
          [1., 1., 0.],
          [1., 0., 1.]]]], requires_grad=True)

In [12]:
conv_layer.bias

Parameter containing:
tensor([-0.1148], requires_grad=True)

In [13]:
# init bias
conv_layer.bias =  nn.Parameter(
    torch.tensor([1], dtype=torch.float32)
)
conv_layer.bias

Parameter containing:
tensor([1.], requires_grad=True)

In [14]:
output = conv_layer(input)
output

tensor([[[10., 14., 10., 14.],
         [15., 12., 14., 11.],
         [13., 18., 12., 15.],
         [13., 14., 14., 19.]]], grad_fn=<SqueezeBackward1>)

**Example 3**

In [15]:
input

tensor([[[2., 2., 1., 4., 1., 0.],
         [0., 4., 0., 3., 3., 4.],
         [0., 4., 1., 2., 0., 0.],
         [2., 1., 4., 1., 3., 1.],
         [4., 3., 1., 4., 2., 4.],
         [2., 0., 0., 4., 3., 4.]]])

In [16]:
# define convolutional layer
conv_layer = nn.Conv2d(
    in_channels=1,
    out_channels=1,
    kernel_size=(2, 3), # create a kernel: 2 x 3
)

In [17]:
init_kernel_weight = torch.randint(
    high=2,
    size=(conv_layer.weight.data.shape),
    dtype=torch.float32
)
init_kernel_weight

tensor([[[[1., 0., 1.],
          [0., 1., 1.]]]])

In [18]:
# init weight & bias
conv_layer.weight.data = init_kernel_weight
conv_layer.weight

Parameter containing:
tensor([[[[1., 0., 1.],
          [0., 1., 1.]]]], requires_grad=True)

In [19]:
conv_layer.bias

Parameter containing:
tensor([0.3672], requires_grad=True)

In [20]:
# init bias
conv_layer.bias =  nn.Parameter(
    torch.tensor([1], dtype=torch.float32)
)
conv_layer.bias

Parameter containing:
tensor([1.], requires_grad=True)

In [21]:
output = conv_layer(input)
output

tensor([[[ 8., 10.,  9., 12.],
         [ 6., 11.,  6.,  8.],
         [ 7., 12.,  6.,  7.],
         [11.,  8., 14.,  9.],
         [ 6., 12., 11., 16.]]], grad_fn=<SqueezeBackward1>)

###**1.2. Padding**

**Example 1**

In [22]:
input = torch.randint(5, (1, 4, 4), dtype=torch.float32)
input

tensor([[[2., 3., 1., 4.],
         [1., 1., 3., 2.],
         [0., 4., 3., 0.],
         [3., 2., 2., 0.]]])

In [23]:
init_kernel_weight = torch.randint(
    high=2,
    size=(conv_layer.weight.data.shape),
    dtype=torch.float32
)
init_kernel_weight

tensor([[[[1., 1., 1.],
          [1., 1., 1.]]]])

In [24]:
# define convolutional layer
conv_layer = nn.Conv2d(
    in_channels=1,
    out_channels=1,
    kernel_size=3, # create a kernel: 3 x 3
    padding='same'
)

In [25]:
conv_layer.weight.data = init_kernel_weight
conv_layer.weight

Parameter containing:
tensor([[[[1., 1., 1.],
          [1., 1., 1.]]]], requires_grad=True)

In [26]:
# init bias
conv_layer.bias =  nn.Parameter(
    torch.tensor([1], dtype=torch.float32)
)
conv_layer.bias

Parameter containing:
tensor([1.], requires_grad=True)

In [27]:
output = conv_layer(input)
output

/usr/local/lib/python3.10/dist-packages/torch/nn/modules/conv.py:456: UserWarning: Using padding='same' with even kernel lengths and odd dilation may require a zero-padded copy of the input be created (Triggered internally at ../aten/src/ATen/native/Convolution.cpp:1008.)
  return F.conv2d(input, weight, bias, self.stride,


tensor([[[ 8., 12., 15., 11.],
         [ 7., 13., 14.,  9.],
         [10., 15., 12.,  6.],
         [ 6.,  8.,  5.,  3.]]], grad_fn=<SqueezeBackward1>)

**Example 2**

In [28]:
input

tensor([[[2., 3., 1., 4.],
         [1., 1., 3., 2.],
         [0., 4., 3., 0.],
         [3., 2., 2., 0.]]])

In [29]:
# define convolutional layer
conv_layer = nn.Conv2d(
    in_channels=1,
    out_channels=1,
    kernel_size=3, # create a kernel: 3 x 3
    padding=(2, 1)
)

In [30]:
conv_layer.weight.data = init_kernel_weight
conv_layer.weight

Parameter containing:
tensor([[[[1., 1., 1.],
          [1., 1., 1.]]]], requires_grad=True)

In [31]:
# init bias
conv_layer.bias =  nn.Parameter(
    torch.tensor([1], dtype=torch.float32)
)
conv_layer.bias

Parameter containing:
tensor([1.], requires_grad=True)

In [32]:
output = conv_layer(input)
output

tensor([[[ 1.,  1.,  1.,  1.],
         [ 6.,  7.,  9.,  6.],
         [ 8., 12., 15., 11.],
         [ 7., 13., 14.,  9.],
         [10., 15., 12.,  6.],
         [ 6.,  8.,  5.,  3.],
         [ 1.,  1.,  1.,  1.]]], grad_fn=<SqueezeBackward1>)

###**1.3. Stride**

**Example 1**

In [33]:
input = torch.randint(5, (1, 6, 6), dtype=torch.float32)
input

tensor([[[3., 4., 1., 2., 1., 0.],
         [4., 0., 2., 4., 1., 2.],
         [3., 1., 0., 1., 3., 1.],
         [3., 0., 1., 4., 0., 0.],
         [4., 0., 2., 0., 3., 3.],
         [2., 2., 2., 1., 3., 2.]]])

In [34]:
# define convolutional layer
conv_layer = nn.Conv2d(
    in_channels=1,
    out_channels=1,
    kernel_size=3, # create a kernel: 3 x 3
    stride=2
)

In [35]:
conv_layer.weight.data = init_kernel_weight
conv_layer.weight

Parameter containing:
tensor([[[[1., 1., 1.],
          [1., 1., 1.]]]], requires_grad=True)

In [36]:
# init bias
conv_layer.bias =  nn.Parameter(
    torch.tensor([1], dtype=torch.float32)
)
conv_layer.bias

Parameter containing:
tensor([1.], requires_grad=True)

In [37]:
output = conv_layer(input)
output

tensor([[[15., 12.],
         [ 9., 10.],
         [13., 12.]]], grad_fn=<SqueezeBackward1>)

**Example 2**

In [38]:
input

tensor([[[3., 4., 1., 2., 1., 0.],
         [4., 0., 2., 4., 1., 2.],
         [3., 1., 0., 1., 3., 1.],
         [3., 0., 1., 4., 0., 0.],
         [4., 0., 2., 0., 3., 3.],
         [2., 2., 2., 1., 3., 2.]]])

In [39]:
# define convolutional layer
conv_layer = nn.Conv2d(
    in_channels=1,
    out_channels=1,
    kernel_size=3, # create a kernel: 3 x 3
    stride=(1, 2)
)

In [40]:
conv_layer.weight.data = init_kernel_weight
conv_layer.weight

Parameter containing:
tensor([[[[1., 1., 1.],
          [1., 1., 1.]]]], requires_grad=True)

In [41]:
# init bias
conv_layer.bias =  nn.Parameter(
    torch.tensor([1], dtype=torch.float32)
)
conv_layer.bias

Parameter containing:
tensor([1.], requires_grad=True)

In [42]:
output = conv_layer(input)
output

tensor([[[15., 12.],
         [11., 12.],
         [ 9., 10.],
         [11., 11.],
         [13., 12.]]], grad_fn=<SqueezeBackward1>)

**Example 3**

In [43]:
input = torch.randint(5, (1, 4, 4), dtype=torch.float32)
input

tensor([[[4., 2., 1., 3.],
         [2., 3., 2., 1.],
         [0., 0., 1., 0.],
         [0., 1., 4., 2.]]])

In [44]:
# define convolutional layer
conv_layer = nn.Conv2d(
    in_channels=1,
    out_channels=1,
    kernel_size=3, # create a kernel: 3 x 3
    padding=1,
    stride=(2, 2)
)

In [45]:
conv_layer.weight.data = init_kernel_weight
conv_layer.weight

Parameter containing:
tensor([[[[1., 1., 1.],
          [1., 1., 1.]]]], requires_grad=True)

In [46]:
# init bias
conv_layer.bias =  nn.Parameter(
    torch.tensor([1], dtype=torch.float32)
)
conv_layer.bias

Parameter containing:
tensor([1.], requires_grad=True)

In [47]:
output = conv_layer(input)
output

tensor([[[7., 7.],
         [6., 8.],
         [2., 8.]]], grad_fn=<SqueezeBackward1>)

**Example 4**

In [48]:
input = torch.randint(5, (1, 5, 7), dtype=torch.float32)
input

tensor([[[4., 4., 3., 4., 2., 0., 4.],
         [4., 1., 4., 0., 3., 2., 4.],
         [0., 1., 0., 2., 0., 3., 3.],
         [4., 1., 3., 1., 4., 1., 0.],
         [3., 0., 1., 2., 4., 4., 0.]]])

In [49]:
# define convolutional layer
conv_layer = nn.Conv2d(
    in_channels=1,
    out_channels=1,
    kernel_size=3, # create a kernel: 3 x 3
    padding=1,
    stride=(2, 2)
)

In [50]:
output = conv_layer(input)
output

tensor([[[-1.1715, -2.5614, -1.9058, -0.5903],
         [-2.5259, -2.5943, -3.5760, -1.8482],
         [-1.1248, -1.4748, -2.2698, -1.4850]]], grad_fn=<SqueezeBackward1>)

##**2. Pooling Layer**

###**2.1. Max Pooling Layer**

**Example 1**

In [51]:
input = torch.randint(5, (1, 6, 6), dtype=torch.float32)
input

tensor([[[3., 4., 2., 3., 3., 0.],
         [0., 2., 4., 3., 4., 3.],
         [1., 2., 0., 3., 4., 2.],
         [2., 1., 3., 2., 0., 3.],
         [2., 3., 2., 2., 2., 0.],
         [4., 2., 2., 3., 2., 4.]]])

In [52]:
max_pool_layer = nn.MaxPool2d(kernel_size=2)

In [53]:
output = max_pool_layer(input)
output

tensor([[[4., 4., 4.],
         [2., 3., 4.],
         [4., 3., 4.]]])

**Example 2**

In [54]:
input

tensor([[[3., 4., 2., 3., 3., 0.],
         [0., 2., 4., 3., 4., 3.],
         [1., 2., 0., 3., 4., 2.],
         [2., 1., 3., 2., 0., 3.],
         [2., 3., 2., 2., 2., 0.],
         [4., 2., 2., 3., 2., 4.]]])

In [55]:
max_pool_layer = nn.MaxPool2d(
    kernel_size=2,
    stride=(1, 2)
)

In [56]:
output = max_pool_layer(input)
output

tensor([[[4., 4., 4.],
         [2., 4., 4.],
         [2., 3., 4.],
         [3., 3., 3.],
         [4., 3., 4.]]])

**Example 3**

In [57]:
input

tensor([[[3., 4., 2., 3., 3., 0.],
         [0., 2., 4., 3., 4., 3.],
         [1., 2., 0., 3., 4., 2.],
         [2., 1., 3., 2., 0., 3.],
         [2., 3., 2., 2., 2., 0.],
         [4., 2., 2., 3., 2., 4.]]])

In [58]:
max_pool_layer = nn.MaxPool2d(
    kernel_size=(2, 3),
    stride=(2, 2),
    padding=1
)

In [59]:
output = max_pool_layer(input)
output

tensor([[[4., 4., 3.],
         [2., 4., 4.],
         [3., 3., 3.],
         [4., 3., 4.]]])

**Example 4: MaxPool1d**

In [60]:
input

tensor([[[3., 4., 2., 3., 3., 0.],
         [0., 2., 4., 3., 4., 3.],
         [1., 2., 0., 3., 4., 2.],
         [2., 1., 3., 2., 0., 3.],
         [2., 3., 2., 2., 2., 0.],
         [4., 2., 2., 3., 2., 4.]]])

In [61]:
max_pool_layer = nn.MaxPool1d(
    kernel_size=3,
    stride=3
)

In [62]:
max_pool_layer(input)

tensor([[[4., 3.],
         [4., 4.],
         [2., 4.],
         [3., 3.],
         [3., 2.],
         [4., 4.]]])

###**2.2. Average Pooling Layer**

**Example 1**

In [63]:
input

tensor([[[3., 4., 2., 3., 3., 0.],
         [0., 2., 4., 3., 4., 3.],
         [1., 2., 0., 3., 4., 2.],
         [2., 1., 3., 2., 0., 3.],
         [2., 3., 2., 2., 2., 0.],
         [4., 2., 2., 3., 2., 4.]]])

In [64]:
avg_pool_layer = nn.AvgPool2d(
    kernel_size=(3, 2),
    stride=(2, 2)
)

In [65]:
output = avg_pool_layer(input)
output

tensor([[[2.0000, 2.5000, 2.6667],
         [1.8333, 2.0000, 1.8333]]])

**Example 2**

In [66]:
input

tensor([[[3., 4., 2., 3., 3., 0.],
         [0., 2., 4., 3., 4., 3.],
         [1., 2., 0., 3., 4., 2.],
         [2., 1., 3., 2., 0., 3.],
         [2., 3., 2., 2., 2., 0.],
         [4., 2., 2., 3., 2., 4.]]])

In [67]:
avg_pool_layer = nn.AvgPool1d(
    kernel_size=3,
    stride=3
)

In [68]:
output = avg_pool_layer(input)
output

tensor([[[3.0000, 2.0000],
         [2.0000, 3.3333],
         [1.0000, 3.0000],
         [2.0000, 1.6667],
         [2.3333, 1.3333],
         [2.6667, 3.0000]]])

##**3. Flatten**

In [69]:
input = torch.randint(5, (1, 3, 2), dtype=torch.float32)
input

tensor([[[3., 0.],
         [4., 2.],
         [2., 1.]]])

In [70]:
flatten_layer = nn.Flatten()

In [71]:
output = flatten_layer(input)
output

tensor([[3., 0., 4., 2., 2., 1.]])

# Excercise

### Ex01

In [72]:
# input
input = torch.tensor([[[2., 2., 1., 4., 1., 0.],
                       [0., 4., 0., 3., 3., 4.],
                       [0., 4., 1., 2., 0., 0.],
                       [2., 1., 4., 1., 3., 1.]]])

# define convolutional layer
conv_layer = nn.Conv2d(
    in_channels=1,
    out_channels=1,
    kernel_size=3, # create a kernel: 3 x 3
    bias=False
)

In [73]:
init_kernel_weight = torch.tensor([[[[1., 1., 0.],
                                     [1., 0., 0.],
                                     [0., 0., 0.]]]])

init_kernel_weight

tensor([[[[1., 1., 0.],
          [1., 0., 0.],
          [0., 0., 0.]]]])

In [74]:
# init weight
conv_layer.weight.data = init_kernel_weight
conv_layer.weight

Parameter containing:
tensor([[[[1., 1., 0.],
          [1., 0., 0.],
          [0., 0., 0.]]]], requires_grad=True)

In [75]:
output = conv_layer(input)
output

tensor([[[4., 7., 5., 8.],
         [4., 8., 4., 8.]]], grad_fn=<SqueezeBackward1>)

In [76]:
# init bias
conv_layer.bias =  nn.Parameter(
    torch.tensor([2], dtype=torch.float32)
)
conv_layer.bias

Parameter containing:
tensor([2.], requires_grad=True)

In [77]:
output = conv_layer(input)
output


tensor([[[ 6.,  9.,  7., 10.],
         [ 6., 10.,  6., 10.]]], grad_fn=<SqueezeBackward1>)

### Ex02

In [78]:
# input
input = torch.tensor([[[2., 4., 2.],
                       [3., 3., 4.],
                       [3., 2., 0.],
                       [4., 0., 4.],
                       [1., 4., 0.]]])

# define convolutional layer
conv_layer = nn.Conv2d(
    in_channels=1,
    out_channels=1,
    kernel_size=3, # create a kernel: 3 x 3
    bias=False,
    padding=1
)

In [79]:
input

tensor([[[2., 4., 2.],
         [3., 3., 4.],
         [3., 2., 0.],
         [4., 0., 4.],
         [1., 4., 0.]]])

In [80]:
init_kernel_weight = torch.tensor([[[[1., 0., 1.],
                                     [1., 1., 1.],
                                     [0., 1., 0.]]]])

init_kernel_weight

tensor([[[[1., 0., 1.],
          [1., 1., 1.],
          [0., 1., 0.]]]])

In [81]:
# init weight
conv_layer.weight.data = init_kernel_weight
conv_layer.weight

Parameter containing:
tensor([[[[1., 0., 1.],
          [1., 1., 1.],
          [0., 1., 0.]]]], requires_grad=True)

In [82]:
# init bias
conv_layer.bias =  nn.Parameter(
    torch.tensor([2], dtype=torch.float32)
)
conv_layer.bias

Parameter containing:
tensor([2.], requires_grad=True)

In [83]:
output = conv_layer(input)
output

tensor([[[11., 13., 12.],
         [15., 18., 13.],
         [14., 14., 11.],
         [ 9., 17.,  8.],
         [ 7., 15.,  6.]]], grad_fn=<SqueezeBackward1>)

In [84]:
conv_layer.stride = (2, 2)

In [85]:
output = conv_layer(input)
output

tensor([[[11., 12.],
         [14., 11.],
         [ 7.,  6.]]], grad_fn=<SqueezeBackward1>)

### Ex03 - Conv + Pooling

In [86]:
# input
input = torch.tensor([[[2., 4., 2.],
                       [1., 3., 2.],
                       [3., 2., 1.],
                       [0., 0., 1.],
                       [0., 0., 1.]]])
# define convolutional layer
conv_layer = nn.Conv2d(
    in_channels=1,
    out_channels=1,
    kernel_size=(3,2), # create a kernel: 3 x 3
    bias=False,
)

In [87]:
input

tensor([[[2., 4., 2.],
         [1., 3., 2.],
         [3., 2., 1.],
         [0., 0., 1.],
         [0., 0., 1.]]])

In [88]:
init_kernel_weight = torch.tensor([[[[1., 1.],
                                     [1., 0.],
                                     [0., 0.]]]])

init_kernel_weight

tensor([[[[1., 1.],
          [1., 0.],
          [0., 0.]]]])

In [89]:
# init weight
conv_layer.weight.data = init_kernel_weight
conv_layer.weight

Parameter containing:
tensor([[[[1., 1.],
          [1., 0.],
          [0., 0.]]]], requires_grad=True)

In [90]:
# init bias
conv_layer.bias =  nn.Parameter(
    torch.tensor([1], dtype=torch.float32)
)
conv_layer.bias

Parameter containing:
tensor([1.], requires_grad=True)

In [91]:
max_pool_layer = nn.MaxPool2d(kernel_size=(1, 2))
avg_pool_layer = nn.AvgPool2d(kernel_size=(1, 2))

output = conv_layer(input)
output

tensor([[[ 8., 10.],
         [ 8.,  8.],
         [ 6.,  4.]]], grad_fn=<SqueezeBackward1>)

In [92]:
max_pool_layer(output)

tensor([[[10.],
         [ 8.],
         [ 6.]]], grad_fn=<MaxPool2DWithIndicesBackward0>)

In [93]:
avg_pool_layer(output)

tensor([[[9.],
         [8.],
         [5.]]], grad_fn=<AvgPool2DBackward0>)

### Ex04 - Convolutions on Gray Scale Images

In [94]:
# define convolutional layer
conv_layer = nn.Conv2d(
    in_channels=1,
    out_channels=1,
    kernel_size=(3,3), # create a kernel: 3 x 3
    bias=False,
)

In [95]:
!gdown 12Q7SpIVm4W2hT6QsiEuARLl5xXKMK8pE

Downloading...
From: https://drive.google.com/uc?id=12Q7SpIVm4W2hT6QsiEuARLl5xXKMK8pE
To: /content/test.csv
100% 51.1M/51.1M [00:01<00:00, 35.4MB/s]


In [96]:
import pandas as pd
import numpy as np
import cv2

test_df = pd.read_csv("test.csv")

In [97]:
img = np.array(test_df.iloc[1].values).astype(np.uint8).reshape((28, 28))
img.shape

(28, 28)

In [98]:
resized_img =  cv2.resize(img, (7, 7))
resized_img.shape

(7, 7)

In [99]:
resized_img

array([[  0,   0,   0,   0,   0,   0,   0],
       [  0,   0,   0,  43,  43,   0,   0],
       [  0,  30, 250, 230, 125, 251,   0],
       [  0, 191,  38,   0,   0,  81,   0],
       [  0, 241,   0,  35, 119, 250,   0],
       [  0,  49, 193, 198,  83,   0,   0],
       [  0,   0,   0,   0,   0,   0,   0]], dtype=uint8)

In [100]:
tensor_img = torch.tensor(resized_img).resize(1, 1, 7 , 7).float()

/usr/local/lib/python3.10/dist-packages/torch/_tensor.py:836: UserWarning: non-inplace resize is deprecated
  warnings.warn("non-inplace resize is deprecated")


In [101]:
kernel_weight = nn.Parameter(torch.tensor([[[[1., 0. , 1.],
                                            [1., 0., -1.],
                                            [1., 0., -1.]]]]))
conv_layer.weight = kernel_weight
conv_layer.weight

Parameter containing:
tensor([[[[ 1.,  0.,  1.],
          [ 1.,  0., -1.],
          [ 1.,  0., -1.]]]], requires_grad=True)

In [102]:
tensor_img

tensor([[[[  0.,   0.,   0.,   0.,   0.,   0.,   0.],
          [  0.,   0.,   0.,  43.,  43.,   0.,   0.],
          [  0.,  30., 250., 230., 125., 251.,   0.],
          [  0., 191.,  38.,   0.,   0.,  81.,   0.],
          [  0., 241.,   0.,  35., 119., 250.,   0.],
          [  0.,  49., 193., 198.,  83.,   0.,   0.],
          [  0.,   0.,   0.,   0.,   0.,   0.,   0.]]]])

In [103]:
max_pool_layer = nn.MaxPool2d(kernel_size=(2, 2))

output = max_pool_layer(tensor_img)
output

tensor([[[[  0.,  43.,  43.],
          [191., 250., 251.],
          [241., 198., 250.]]]])

In [104]:
output = conv_layer(tensor_img)
output

tensor([[[[-250., -243.,   82.,   22.,  168.],
          [-288.,   34.,  206.,  -59.,  168.],
          [ 212.,  657.,  294.,  185.,  244.],
          [-155.,  248.,   29.,   64.,  202.],
          [-193.,  127.,  229.,  483.,  202.]]]],
       grad_fn=<ConvolutionBackward0>)

In [105]:
max_pool_layer = nn.MaxPool2d(kernel_size=(2, 2))

max_pool_layer(output)

tensor([[[[ 34., 206.],
          [657., 294.]]]], grad_fn=<MaxPool2DWithIndicesBackward0>)